#include <stdint.h>

#include "audio.h"
#include "vswap.h"

#define CW_LEVELS 100
#pragma pack(push, 1)
typedef struct
{
	uint16_t magic;
	int32_t ptr[CW_LEVELS];
} CWMapHead;
typedef struct
{
	uint32_t offPlane0;
	uint32_t offPlane1;
	uint32_t offPlane2;
	uint16_t lenPlane0;
	uint16_t lenPlane1;
	uint16_t lenPlane2;
	uint16_t width;
	uint16_t height;
	char name[16];
	char signature[4];
} CWLevelHead;
#pragma pack(pop)

#define NUM_PLANES 3
typedef struct
{
	int len;
	uint16_t *plane;
} CWPlane;
typedef struct
{
	CWLevelHead header;
	CWPlane planes[NUM_PLANES];
} CWLevel;

typedef struct
{
	CWMapHead mapHead;
	CWLevel *levels;
	int nLevels;
	CWAudio audio;
	CWVSwap vswap;
} CWolfMap;

int CWLoad(CWolfMap *map, const char *path);
void CWFree(CWolfMap *map);

typedef enum
{
	CWTILE_WALL,
	CWTILE_DOOR_V,
	CWTILE_DOOR_H,
	CWTILE_DOOR_GOLD_V,
	CWTILE_DOOR_GOLD_H,
	CWTILE_DOOR_SILVER_V,
	CWTILE_DOOR_SILVER_H,
	CWTILE_ELEVATOR_V,
	CWTILE_ELEVATOR_H,
	CWTILE_AREA,
	CWTILE_UNKNOWN,
} CWTile;

typedef enum
{
	CWENT_PLAYER_SPAWN_N,
	CWENT_PLAYER_SPAWN_E,
	CWENT_PLAYER_SPAWN_S,
	CWENT_PLAYER_SPAWN_W,
	CWENT_PROP,
	CWENT_DOG_FOOD,
	CWENT_KEY_SILVER,
	CWENT_KEY_GOLD,
	CWENT_MEAL,
	CWENT_MEDKIT,
	CWENT_AMMO,
	CWENT_MACHINE_GUN,
	CWENT_CHAIN_GUN,
	CWENT_CROSS,
	CWENT_CHALICE,
	CWENT_CHEST,
	CWENT_CROWN,
	CWENT_LIFE,
	CWENT_PUSHWALL,
	CWENT_DEAD_GUARD,

	CWENT_GUARD_STAND_N,
	CWENT_GUARD_STAND_E,
	CWENT_GUARD_STAND_S,
	CWENT_GUARD_STAND_W,
	CWENT_OFFICER_STAND_N,
	CWENT_OFFICER_STAND_E,
	CWENT_OFFICER_STAND_S,
	CWENT_OFFICER_STAND_W,
	CWENT_SS_STAND_N,
	CWENT_SS_STAND_E,
	CWENT_SS_STAND_S,
	CWENT_SS_STAND_W,
	CWENT_DOG_STAND_N,
	CWENT_DOG_STAND_E,
	CWENT_DOG_STAND_S,
	CWENT_DOG_STAND_W,
	CWENT_MUTANT_STAND_N,
	CWENT_MUTANT_STAND_E,
	CWENT_MUTANT_STAND_S,
	CWENT_MUTANT_STAND_W,
	CWENT_GUARD_PATROL_N,
	CWENT_GUARD_PATROL_E,
	CWENT_GUARD_PATROL_S,
	CWENT_GUARD_PATROL_W,
	CWENT_OFFICER_PATROL_N,
	CWENT_OFFICER_PATROL_E,
	CWENT_OFFICER_PATROL_S,
	CWENT_OFFICER_PATROL_W,
	CWENT_SS_PATROL_N,
	CWENT_SS_PATROL_E,
	CWENT_SS_PATROL_S,
	CWENT_SS_PATROL_W,
	CWENT_DOG_PATROL_N,
	CWENT_DOG_PATROL_E,
	CWENT_DOG_PATROL_S,
	CWENT_DOG_PATROL_W,
	CWENT_MUTANT_PATROL_N,
	CWENT_MUTANT_PATROL_E,
	CWENT_MUTANT_PATROL_S,
	CWENT_MUTANT_PATROL_W,

	CWENT_FAKE_HITLER,
	CWENT_HITLER,
	CWENT_FAT,
	CWENT_SCHABBS,
	CWENT_GRETEL,
	CWENT_HANSEL,
	CWENT_GIFT,
	CWENT_GHOST_N,
	CWENT_GHOST_E,
	CWENT_GHOST_S,
	CWENT_GHOST_W,
	CWENT_SPECTRE,
	CWENT_ANGEL,
	CWENT_TRANS,
	CWENT_UBER,
	CWENT_WILL,
	CWENT_DEATH,

	CWENT_UNKNOWN,
} CWEntity;

typedef enum
{
	CWWALL_GREY_BRICK_1,
	CWWALL_GREY_BRICK_2,
	CWWALL_GREY_BRICK_FLAG,
	CWWALL_GREY_BRICK_HITLER,
	CWWALL_CELL,
	CWWALL_GREY_BRICK_EAGLE,
	CWWALL_CELL_SKELETON,
	CWWALL_BLUE_BRICK_1,
	CWWALL_BLUE_BRICK_2,
	CWWALL_WOOD_EAGLE,
	CWWALL_WOOD_HITLER,
	CWWALL_WOOD,
	CWWALL_ENTRANCE,
	CWWALL_STEEL,
	CWWALL_LANDSCAPE,
	CWWALL_RED_BRICK,
	CWWALL_RED_BRICK_SWASTIKA,
	CWWALL_PURPLE,
	CWWALL_RED_BRICK_FLAG,
	CWWALL_ELEVATOR,
	CWWALL_PURPLE_BLOOD,
	CWWALL_UNKNOWN
} CWWall;

uint16_t CWLevelGetCh(
	const CWLevel *level, const int planeIndex, const int x, const int y);
CWTile CWChToTile(const uint16_t ch);
CWWall CWChToWall(const uint16_t ch);
CWEntity CWLevelGetEntity(const CWLevel *level, const int x, const int y);
