name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Homebrew
      id: set-up-homebrew
      if: matrix.os == 'ubuntu-latest'
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install SDL via homebrew
      # Because ubuntu 22 doesn't have the latest SDL libs
      if: matrix.os == 'ubuntu-latest'
      run: brew install sdl2 sdl2_mixer sdl2_image

    - name: Install packages Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt install gcc-10 g++-10
      # sudo apt install libsdl2-dev libsdl2-mixer-dev gcc-10 g++-10
    - name: Install packages macOS
      if: matrix.os == 'macos-latest'
      run: |
        sh macosx/install-sdl2.sh
  
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Wno-dev .

    - name: Build
      # Build your program with the given configuration
      run: make -j2
